<h1>Faça seu login</h1>

<div class="row">
	<div class="col-md-6">

		<?php
		$title = $form->get ( 'username' );
		$title->setAttribute ( 'class', 'form-control' )->setLabelAttributes ( [ 
				'class' => 'control-label' 
		] );
		
		$content = $form->get ( 'password' );
		$content->setAttribute ( 'class', 'form-control' )->setLabelAttributes ( [ 
				'class' => 'control-label' 
		] );
		
		$submit = $form->get ( 'submit' );
		$submit->setAttribute ( 'class', 'btn btn-primary' );
		
		$form->setAttribute ( 'action', $this->url ( 'login' ) );
		$form->prepare ();
		
		echo $this->form ()->openTag ( $form );
		?>
		<?php if($messageError):?>
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<strong>Error!</strong> <?= $messageError?>
		</div>
		<?php endif;?>
	
		<div class="form-group">
			<?= $this->formLabel($title)?>
			<?= $this->formElement($title)?>
		</div>
	
			<div class="form-group">
			<?= $this->formLabel($content)?>
			<?= $this->formElement($content)?>
		</div>
	
		<?php
		echo $this->formSubmit ( $submit );
		echo $this->form ()->closeTag ();
		?>
	</div>
</div>