<?php
	$this->headTitle("Blog");
?>
<h1>Hello Word</h1>

<p>
	<a href="<?= $this->url('admin-blog/post', ['action' => 'add']); ?>">
		New Post
	</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($posts as $post): ?>
			<tr>
				<td><?= $this->escapeHtml($post->title) ?></td>
				<td>
					<a href="<?= $this->url('admin-blog/post', ['action' => 'edit', 'id' => $post->id]);?>">
						Edit
					</a>
					<a href="<?= $this->url('admin-blog/post', ['action' => 'delete', 'id' => $post->id]);?>">
						Delete
					</a>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>